# action.yml
name: 'Git Meta'
description: 'Creates a /tmp/meta file containing git meta information.'
inputs:
  actor:
    description: 'Actor'
    required: true
    default: ${{ github.actor }}
  message:
    description: 'Commit Message'
    required: true
    default: ${{ github.actor }}
runs:
  using: 'docker'
  image: 'Dockerfile'
