# action.yml
name: 'Git Meta'
description: 'Creates a /tmp/meta file containing git meta information.'
inputs:
  metafile:
    description: 'Meta file path to write the git meta to'
    required: true
    default: git-meta
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.metafile }}
