on: [push]

jobs:
  metajob:
    runs-on: ubuntu-latest
    name: A job to generate some files man!
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Test myself
        uses: ./ # Uses an action in the root directory
        id: meta
        with:
          metafile: meta
      - name: Verify ok
        id: test-myself
        run: |
          echo "VERSION ENV $VERSION"
          echo "version output: ${{ steps.meta.outputs.version  }}"
          cat meta
